version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # ホットリロード対応
    environment:
      - ENV=development
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]